### ISSUE TITLE
Error: Could not find or load main class

### ISSUE THREAD

**Issue by jozefcifre** [MovingBlocks/box2d-editor#48]
* Operating System: NixOS GNOME Wayland

I just cloned the git repo in my DestinationSol directory, but the editor won't run due to some error.

How to reproduce:

* Step 1: [On NixOS] create the following shell.nix file in your directory to get the missing libraries.
```nix
let
  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-23.05";
#  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-unstable"; # <- this doesn't work either
  pkgs = import nixpkgs { config = {}; overlays = []; };
in

pkgs.mkShell {
  packages = with pkgs; [
    git
    temurin-bin-11
    libglvnd
    libpulseaudio
    xorg.libXcursor
    xorg.libXrandr
    xorg.libXxf86vm
  ];

  LD_LIBRARY_PATH = "${pkgs.stdenv.cc.cc.lib}/lib:${pkgs.libglvnd}/lib:${pkgs.libpulseaudio}/lib:${pkgs.xorg.libXcursor}/lib:${pkgs.xorg.libXrandr}/lib:${pkgs.xorg.libXxf86vm}/lib";
}
```

* Step 2: Make the shell: $ `nix-shell shell.nix`
When in the nix shell environment, try to run the editor like this:

- git clone https://github.com/MovingBlocks/box2d-editor -b gradle-libgdx-upgrade
- cd box2d-editor
- ./gradlew :editor:run

```
[nix-shell:~/.../box2d-editor/]$ git clone https://github.com/MovingBlocks/box2d-editor -b gradle-libgdx-upgrade
[nix-shell:~/.../box2d-editor/]$ cd box2d-editor
[nix-shell:~/.../box2d-editor/]$ ./gradlew :editor:run
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

Any suggestions on how to fix this?

**Comment by BenjaminAmos** [comment]
It might have been because I forgot to update the gradle wrapper (`gradlew`). Could you `git pull` the latest changes (cb08d3a7cd1af929936f1824cb81c53a42339d36 in particular) and try `./gradlew :editor:run` again?

**Comment by jozefcifre** [comment]
> It might have been because I forgot to update the gradle wrapper (`gradlew`). Could you `git pull` the latest changes ([cb08d3a](https://github.com/MovingBlocks/box2d-editor/commit/cb08d3a7cd1af929936f1824cb81c53a42339d36) in particular) and try `./gradlew :editor:run` again?

How?

**Comment by jozefcifre** [comment]
> It might have been because I forgot to update the gradle wrapper (`gradlew`). Could you `git pull` the latest changes ([cb08d3a](https://github.com/MovingBlocks/box2d-editor/commit/cb08d3a7cd1af929936f1824cb81c53a42339d36) in particular) and try `./gradlew :editor:run` again?

Idk, but git says my clone is up-to-date.
```
box2d-editor]$ git status
On branch gradle-libgdx-upgrade
Your branch is up to date with 'origin/gradle-libgdx-upgrade'.

nothing to commit, working tree clean
```

I keep getting the error 
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

**Comment by BenjaminAmos** [comment]
If running `git rev-parse --short HEAD` returns `cb08d3a` then you're up to date. Otherwise, you can run `git pull` to pull-in the latest changes. If you can run `gradlew` for Destination Sol then I'm not sure why it wouldn't work here.

**Comment by jozefcifre** [comment]
Btw, the issue happened when I cloned the repo inside the DestinationSol directory, is that why it didn't work?

I've just cloned the editor outside and now it runs.
```
/box2d-editor]$ ./gradlew :editor:run
Downloading https://services.gradle.org/distributions/gradle-8.4-bin.zip
............10%............20%.............30%............40%.............50%............60%.............70%............80%.............90%............100%

Welcome to Gradle 8.4!

Here are the highlights of this release:
 - Compiling and testing with Java 21
 - Faster Java compilation on Windows
 - Role focused dependency configurations creation

For more details see https://docs.gradle.org/8.4/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.

> Task :editor:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :editor:processResources
> Task :editor:classes

> Task :editor:run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/jvucq/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
LwjglGraphics: created OpenGL 3.2+ core profile (GLES 3.0) context. This is experimental!
```
![image](https://github.com/MovingBlocks/box2d-editor/assets/124826525/402cbb20-1c84-4cab-ac49-c3f786d23d40)

**Comment by jozefcifre** [comment]
> If running `git rev-parse --short HEAD` returns `cb08d3a` then you're up to date. Otherwise, you can run `git pull` to pull-in the latest changes. If you can run `gradlew` for Destination Sol then I'm not sure why it wouldn't work here.

Done, I am up-to-date and now it works. Thank you.

However, I got some errors, but the editor seems to work, the only issue that I've found is that it apparently does not exit on close or fails to terminate.

[cout.txt](https://github.com/MovingBlocks/box2d-editor/files/13328623/cout.txt)

[hs_err_pid30854.log](https://github.com/MovingBlocks/box2d-editor/files/13328624/hs_err_pid30854.log)

**Comment by BenjaminAmos** [comment]
> However, I got some errors, but the editor seems to work, the only issue that I've found is that it apparently does not exit on close or fails to terminate.

I'm aware of that issue. Since you can use the editor and it only crashes when you try to close it, I've never considered it a priority. I might open another issue about it as a reminder but I probably won't see to it for the moment. Thanks for all your input in identifying flaws!
